### ISSUE TITLE
Your aenea on Ubuntu

### ISSUE THREAD

**Issue by maxim-danilov** [seananderson/aenea-grammars#1]
Hello! Thanks for your fork of aenea. Your code looks good. I like your vim grammars. 
Let me know please does your aenea work with Ubuntu (X11)? Any recommendations to use it on Ubuntu? 

Thank you!  

P.S. 
I tried on my Ubuntu. It almost works but ProxyCustomAppContext throws some error (while compares the window title).

**Comment by seananderson** [comment]
I've never tried them with Ubuntu. For the most part I imagine it would work. Mine is set up to work with the Mac server version of Aenea. The Linux version is the original and is probably more tested https://github.com/dictation-toolbox/aenea . I'm sure there's an equivalent to ProxyCustomAppContext if you dig through the Linux version. There are also lots of examples of grammars for Aenea that should work on Linux. My code is not pretty but it gets the job done for me. 

Some examples of other (much better written) grammars that include Vim for Aenea:
https://github.com/dictation-toolbox/aenea-grammars  (Linux based)
https://github.com/dylan-chong/aenea-setup (Mac based)
